swagger: "2.0"
info:
  description: "This is the swagger file that goes with our server code"
  version: '1.0.0'
  title: "Swagger REST Article"
consumes:
  - "application/json"
produces:
  - "application/json"
basePath: "/api"

paths:
  /people:
     get:
      operationId: "people.read"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          content:
            schema:
              type: "array"
              $ref: "#/definitions/People"


definitions:
  People:
    type: "object"
    properties:
      fname:
        type: "string"
      lname:
        type: "string"
      timestamp:
        type: "string"

